server:
  port: 8002 #指定运行端口
spring:
  application:
    name: eureka-server-01 #指定服务名称
eureka:
  instance:
    hostname: replica2
  client:
    serviceUrl:
      defaultZone: http://replica1:8001/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
